### ISSUE TITLE
Slow performance out of the box on AWS?

### ISSUE THREAD

**Issue by pj4533** [bibanul/tiger-geocoder#5]
I followed the directions exactly for setting up the geocoder, using an r3.xlarge.

If I do a new call (i.e., not cached in redis), here is the resulting curl timings:

```
curl -w "@curl-format.txt" -o /dev/null -s "http://<myip>/geocode/4501%20Cone%20Flower%20Crt,Acworth,GA"
time_namelookup:  0.000
       time_connect:  0.019
    time_appconnect:  0.000
   time_pretransfer:  0.019
      time_redirect:  0.000
 time_starttransfer:  10.394
                    ----------
         time_total:  10.394
```

And for that call, the Postgresql log shows:

```
Interrupt requested
Interrupt requested
2015-07-20 20:56:15 UTC ERROR:  canceling statement due to statement timeout
2015-07-20 20:56:15 UTC CONTEXT:  PL/pgSQL function geocode_address(norm_addy,integer,geometry) line 193 at FOR over EXECUTE statement
	PL/pgSQL function geocode(norm_addy,integer,geometry) line 14 at FOR over SELECT rows
2015-07-20 20:56:15 UTC STATEMENT:  SELECT g.rating, ST_X(g.geomout) As lon, ST_Y(g.geomout) As lat,(addy).address As streetnumber, (addy).streetname As street, (addy).streettypeabbrev As streettype, (addy).location As city, (addy).stateabbrev As state, (addy).zip As zip, (pprint_addy(addy)) As normalized_address FROM geocode(normalize_address($1), $2) As g
```

Looks like something is timing out?

Then the interesting thing is if I just retry the same curl again:

```
Interrupt requested
Interrupt requested
2015-07-20 21:00:39 UTC ERROR:  canceling statement due to statement timeout
2015-07-20 21:00:39 UTC CONTEXT:  PL/pgSQL function geocode_address(norm_addy,integer,geometry) line 193 at FOR over EXECUTE statement
	PL/pgSQL function geocode(norm_addy,integer,geometry) line 14 at FOR over SELECT rows
2015-07-20 21:00:39 UTC STATEMENT:  SELECT g.rating, ST_X(g.geomout) As lon, ST_Y(g.geomout) As lat,(addy).address As streetnumber, (addy).streetname As street, (addy).streettypeabbrev As streettype, (addy).location As city, (addy).stateabbrev As state, (addy).zip As zip, (pprint_addy(addy)) As normalized_address FROM geocode(normalize_address($1), $2) As g
```

Similar results, but tried same request again:

```
2015-07-20 21:00:52 UTC LOG:  duration: 8842.187 ms  execute tiger_geocode_postgis: SELECT g.rating, ST_X(g.geomout) As lon, ST_Y(g.geomout) As lat,(addy).address As streetnumber, (addy).streetname As street, (addy).streettypeabbrev As streettype, (addy).location As city, (addy).stateabbrev As state, (addy).zip As zip, (pprint_addy(addy)) As normalized_address FROM geocode(normalize_address($1), $2) As g
2015-07-20 21:00:52 UTC DETAIL:  parameters: $1 = '4501 Cone Flower Crt,Acworth,GA', $2 = '1'
```

This time it appears to work (yet still took 8.9s).   From that point on, it does appear cached in redis and it is super fast.

So whats going on?  Is something setup wrong?  Any tips?

**Comment by bibanul** [comment]
It does appear that your postgres instance is not tuned for the memory params and/or HDD (EBS). You need to choose SSD EBS (not magnetic drives) from EC2 when configuring the instance. It will be too slow and time out when loading data from HDD into RAM on first hit. Redis is just a normal cache layer but should not be accounted for when you do cold calls against Postgres. Also make sure all is provisioned in SAME EC2 region, else you will access EBS over network and will be super painfully slow. Let me know otherwise if all checks out.

**Comment by pj4533** [comment]
Thanks for the quick response!

I verified the type of volumes are 'gp2'  (General Purpose SSD).   Everything is in us-east-1b.  

I changed the 2 Postgresql settings as per the instructions.  I set shared_buffers to 4GB and effective_cache_size to 24GB.

Any other ideas?

**Comment by bibanul** [comment]
Did you restart postgres after the buffer change etc? I can log in quick. Email me on amazon@efficientdynamicsinc.com and I will email you back my RSA pub key.

**Comment by pj4533** [comment]
Yeah I restarted postgres...also tried using as a 'EBS-Optimized instance'.   Although I didn't do the 'Provisioned SSD' which is supposed to give higher performance...I just stuck with the general purpose SSD that was in the AMI.

Hmmmm.  No sure what else i could tweak...I really didn't do much out of the box, should be easy for you to reproduce this just firing up a new one of these as per the directions.

**Comment by bibanul** [comment]
We have  a significant number of customers using this image as is. There was only one reported incident 2 weeks ago, but that was resolved due to how Postgres starts from Cold boot and loading index/data into the RAM. I can't reproduce this on the EC2 image as you suggest, we tuned it and created that image a while back and was tested and works for everyone. Only way is to allow me to SSH into that machine. You can remove my PEM key at any time after that.

Go ahead psql into the postgres and issue that very query locally on the machine. Tiger loads data by State, hence the few 2-3 queries per state will bring the data into RAM. It should not be 10 seconds definitely. TIGER/postgres non-accelerated via redis works in the 50-175ms response time.

**Comment by pj4533** [comment]
Really weird then...cause i just did the 1-click setup for the AMI, and changed the 2 settings in the postgresql conf.   Not sure if maybe something has changed behind the scenes on AWS....?

Either way, i emailed you.

**Comment by pj4533** [comment]
As per our discussion in email, I tried changing the timeout...which gets rid of the errors, but doesn't help performance.

Your update to the docs says:

"Lately I think starting the AMI from amazon may require you to issue an ANALYZE against the whole geocoder database to re-organize the statistics according to the newly created disk images. This will take potentially few hours to run one time but it's time well spent. "

I'll try this, but is there any chance of you posting an update to the AMI with a properly optimized database? 

Another thought I had was trying the provisioned SSDs with a EBS-optimized instance as those are supposed to have better disk read performance.

**Comment by bibanul** [comment]
The AMI was created with a properly optimized TIGER setup. Any Database indexes are created against physical storage and when you provision a new instance it appears that EBS storage provisioning will require re-indexing of a newly launched AMI. I'm checking this with Amazon folks because it wasn't an issue few months back. However as I explained, half of the issue is cold start on Postgres. Those 24GB of RAM you provisioned need to fill up and the only way is to warm up postgres to load up as much as it can into RAM.

**Comment by pj4533** [comment]
Gotcha, I think the bulk of the issue is preloading RAM.   Would be awesome if there was a script included on the AMI that just did a bunch of requests to prep the instance.  Just a thought.  

I think how I'll deal with this is just sorting my list of requests by zipcode & then geocoding.   I'll take a hit whenever I get to a new area that isn't cached, but I don't plan on leaving the instance running 24/7 anyway, so I'll be running into the RAM issue a bunch.
